# Generated by Django 5.2.1 on 2025-05-14 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodywork',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузовы',
                'db_table': 'bodywork',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'brand',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('sale_active', models.BooleanField(verbose_name='Действие скидки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Описание')),
                ('sale_percent', models.SmallIntegerField(verbose_name='Процент скидки')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала аренды')),
                ('end_date', models.DateTimeField(verbose_name='Дата конца аренды')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'sales',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('mass', models.SmallIntegerField(verbose_name='Масса')),
                ('drive', models.CharField(max_length=20, verbose_name='Привод')),
                ('bodywork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='easy_ride.bodywork', verbose_name='Кузов')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='easy_ride.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
                'db_table': 'car_model',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transmission', models.CharField(max_length=30, verbose_name='Трансмиссия')),
                ('horse_powers', models.SmallIntegerField(verbose_name='Лошадиных сил')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Объем двигателя')),
                ('colour', models.CharField(max_length=50, verbose_name='Цвет')),
                ('is_free', models.BooleanField(verbose_name='Свободен')),
                ('license_plate', models.CharField(max_length=15, verbose_name='Номера')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='easy_ride.carmodels', verbose_name='Модель')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='easy_ride.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'cars',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='easy_ride.sales', verbose_name='Скидка'),
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_num', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('age', models.SmallIntegerField(verbose_name='Возраст')),
                ('passport_series', models.SmallIntegerField(verbose_name='Серия паспорта')),
                ('passport_num', models.IntegerField(verbose_name='Номер паспорта')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
                'db_table': 'user_information',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_published', models.BooleanField(blank=True, null=True, verbose_name='Опобликован')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='easy_ride.userinformation', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала аренды')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала аренды')),
                ('end_date', models.DateTimeField(verbose_name='Дата конца аренды')),
                ('accepted', models.BooleanField(blank=True, null=True, verbose_name='Подтверждение')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='easy_ride.cars', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='easy_ride.userinformation', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'db_table': 'rent',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
