# Generated by Django 5.2.1 on 2025-05-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_ride', '0003_cars_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
