# Generated by Django 5.2.1 on 2025-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_ride', '0004_cars_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость'),
        ),
    ]
