# Generated by Django 5.2.1 on 2025-05-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_ride', '0005_cars_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
