# Generated by Django 5.2.1 on 2025-05-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_ride', '0007_sales_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
    ]
